# docs: https://embarkstudios.github.io/cargo-deny/
[advisories]
vulnerability = "deny"
unmaintained = "deny"
unsound = "deny"
yanked = "deny"
ignore = []

[bans]
multiple-versions = "deny"
wildcards = "deny"
deny = []
skip = []
skip-tree = []

[licenses]
# Default stance: deny unless allowed
default = "deny"
copyleft = "deny"
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Zlib",
    "Unicode-DFS-2016",
]
exceptions = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []