# cargo-audit configuration
# Ignore Linux-only dependencies (GTK, webkit2gtk, etc.) for macOS-only app

[advisories]
ignore = [
    # GTK3 bindings - Linux only, not used on macOS
    "RUSTSEC-2024-0411",  # gdkwayland-sys
    "RUSTSEC-2024-0412",  # gdk
    "RUSTSEC-2024-0413",  # atk
    "RUSTSEC-2024-0414",  # gdkx11-sys
    "RUSTSEC-2024-0415",  # gtk
    "RUSTSEC-2024-0416",  # atk-sys
    "RUSTSEC-2024-0417",  # gdkx11
    "RUSTSEC-2024-0418",  # gdk-sys
    "RUSTSEC-2024-0419",  # gtk3-macros
    "RUSTSEC-2024-0420",  # gtk-sys
    "RUSTSEC-2024-0429",  # glib (unsound Iterator)

    # Unmaintained crates from transitive Tauri dependencies
    "RUSTSEC-2024-0370",  # proc-macro-error
    "RUSTSEC-2024-0384",  # instant
    "RUSTSEC-2024-0388",  # derivative
    "RUSTSEC-2024-0436",  # paste
    "RUSTSEC-2025-0057",  # fxhash

    # unic-* crates (unmaintained but stable)
    "RUSTSEC-2025-0075",  # unic-char-range
    "RUSTSEC-2025-0080",  # unic-common
    "RUSTSEC-2025-0081",  # unic-char-property
    "RUSTSEC-2025-0098",  # unic-ucd-version
    "RUSTSEC-2025-0100",  # unic-ucd-ident
]
