# Treat warnings as errors everywhere.
[build]
rustflags = ["-Dwarnings"]

[alias]
# Strict linting helpers
lint = "clippy -- -D warnings -D clippy::all -D clippy::pedantic -D clippy::nursery"
fmt-check = "fmt --all -- --check"

# Development automation tasks (use: `cargo xtask <command>`)
xtask = "run --package xtask --"

# Convenient shortcuts for common xtask commands
ci = "xtask ci"
check-all = "xtask ci"

# Extra hardening for Linux (ignored on macOS/Windows)
[target.'cfg(target_os = "linux")']
rustflags = [
  "-C", "link-arg=-Wl,-z,relro",
  "-C", "link-arg=-Wl,-z,now",
  "-C", "link-arg=-Wl,--as-needed",
]