use pulsearc_domain::WbsElement;

/// Returns a deterministic set of WBS elements mirroring the legacy SAP cache
/// fixtures. Useful for fast-path project matcher tests.
pub fn sample_wbs_elements() -> Vec<WbsElement> {
    vec![
        WbsElement {
            wbs_code: "USC0063201.1.0".into(),
            project_def: "USC0063201".into(),
            project_name: Some("Project Astro".into()),
            description: Some("Acquire Stellar Corp".into()),
            status: "REL".into(),
            cached_at: 1_700_000_000,
            opportunity_id: Some("opp_astro".into()),
            deal_name: Some("Astro Acquisition".into()),
            target_company_name: Some("Stellar Corp".into()),
            counterparty: Some("Stellar Corp".into()),
            industry: Some("Aerospace".into()),
            region: Some("NA".into()),
            amount: Some(125_000_000.0),
            stage_name: Some("Negotiation".into()),
            project_code: Some("USC0063201".into()),
        },
        WbsElement {
            wbs_code: "USC0074892.2.0".into(),
            project_def: "USC0074892".into(),
            project_name: Some("Operation Neptune".into()),
            description: Some("Merge with AquaTech".into()),
            status: "REL".into(),
            cached_at: 1_700_000_000,
            opportunity_id: Some("opp_neptune".into()),
            deal_name: Some("Neptune Merger".into()),
            target_company_name: Some("AquaTech".into()),
            counterparty: Some("AquaTech".into()),
            industry: Some("Marine".into()),
            region: Some("EMEA".into()),
            amount: Some(86_500_000.0),
            stage_name: Some("Due Diligence".into()),
            project_code: Some("USC0074892".into()),
        },
        WbsElement {
            wbs_code: "USC0089123.5.0".into(),
            project_def: "USC0089123".into(),
            project_name: Some("Alpha Initiative".into()),
            description: Some("Invest in AlphaTech".into()),
            status: "REL".into(),
            cached_at: 1_700_000_000,
            opportunity_id: Some("opp_alpha".into()),
            deal_name: Some("AlphaTech Investment".into()),
            target_company_name: Some("AlphaTech".into()),
            counterparty: Some("AlphaTech".into()),
            industry: Some("Software".into()),
            region: Some("APAC".into()),
            amount: Some(42_000_000.0),
            stage_name: Some("Evaluation".into()),
            project_code: Some("USC0089123".into()),
        },
        WbsElement {
            wbs_code: "USC0012345.1.0".into(),
            project_def: "USC0012345".into(),
            project_name: Some("Beta Program".into()),
            description: Some("Partner with BetaCo".into()),
            status: "REL".into(),
            cached_at: 1_700_000_000,
            opportunity_id: Some("opp_beta".into()),
            deal_name: Some("BetaCo Partnership".into()),
            target_company_name: Some("BetaCo".into()),
            counterparty: Some("BetaCo".into()),
            industry: Some("Consulting".into()),
            region: Some("LATAM".into()),
            amount: Some(24_750_000.0),
            stage_name: Some("Qualification".into()),
            project_code: Some("USC0012345".into()),
        },
    ]
}
